# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  ğŸ‘‹ Thanks for opening your first issue! If you're reporting a ğŸ bug, please make sure
  you include steps to reproduce it. If you're requesting a feature ğŸ, please provide real
  use cases that would benefit. ğŸ‘ª

  To help make this a smooth process, please be sure you have first read the
  [contributing guidelines](https://github.com/kong/insomnia/blob/master/CONTRIBUTING.md).

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  ğŸ’– Thanks for opening this pull request! ğŸ’–

  To help make this a smooth process, please be sure you have first read the
  [contributing guidelines](https://github.com/kong/insomnia/blob/master/CONTRIBUTING.md).

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰ You're helping make Insomnia awesome! ğŸ™Œ
