version: '3'
services:
  package_linux:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile.Ubuntu14'
    environment:
    - 'NODELIBCURL_BUILD_STATIC=yes'
    - 'BUILD_TARGETS=AppImage,deb,tar.gz,rpm'
    - 'KEEP_DIST_FOLDER=yes'
    volumes:
    - ./packages/insomnia-app/dist:/src/insomnia/packages/insomnia-app/dist
  package_snap:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile.Ubuntu16'
    environment:
    - 'NODELIBCURL_BUILD_STATIC=yes'
    - 'BUILD_TARGETS=snap'
    - 'KEEP_DIST_FOLDER=yes'
    volumes:
    - ./packages/insomnia-app/dist:/src/insomnia/packages/insomnia-app/dist
