[build]
  base = "website"
  publish = "website/_speedpack"
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.30"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.30"
