name: Encode

on:
  workflow_dispatch:

jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch # Check out the release branch
        uses: actions/checkout@v4
        
      - name: Sha256 of asset containing secret file path
        id: sha256
        run: |
          md_binary_artifacts=$(find "." -type f \
          \( -name "*.md" \) \
          -exec sha256sum {} \;)

           echo "Found artifacts: ${md_binary_artifacts}"
           
          trimmed_md_binary_artifacts=$(echo "${md_binary_artifacts}" | sed "s/\(.* \)\(.*\/\(.*\)\)/\1\\3/" | sort)
          echo "Trimmed: ${trimmed_md_binary_artifacts}"
          
          md_binary_artifact_digest_base64=$(echo "${trimmed_md_binary_artifacts}" | base64 -w0)
          got=$(echo "${md_binary_artifact_digest_base64}" | base64 -d)
          
          echo "md_binary_artifact_digest_base64=${md_binary_artifact_digest_base64}" >> $GITHUB_OUTPUT
          
          echo "Digest ${md_binary_artifact_digest_base64}"
          echo "Expected Artifacts: ${md_binary_artifacts}"
          echo "Got Artifacts: ${got}"
        env:
          ORG: ${{secrets.ORG}}
          PROJECT: ${{secrets.PROJECT}}
          INSOMNIA_TOKEN: ${{secrets.INSOMNIA_TOKEN}}

          
      - name: set
        id: set
        run: |

          test="20fb80760912f56c83d3a53de7e3db7087708949a99e15011b9bc1bd9e358775  Insomnia.Core-9.3.0-alpha.3.rpm 
          240ea5b1c3bbfa666318713fdb6c50649bcbe61ab8a307ba52fb6a983cddaa2b  Insomnia.Core-9.3.0-alpha.3.snap
          3aafe450b46e9e30aef192c43f3a6420179a562d7a9ad497c3ad2cc179ebaa63  Insomnia.Core-9.3.0-alpha.3.tar.gz
          409eeefd0167fc42a3b44cc4bdeca8a23542b82626bb572f174dc9ca612fc2fc  Insomnia.Core-9.3.0-alpha.3.deb 
          64f06151cd88c7e4afef4a59adb02cee078ac315050a43923df5b54eaa24fe23  Insomnia.Core-9.3.0-alpha.3.dmg 
          895984cb94ff9b826f70e0211a98eb4f70c035087857dd906e55336c419527ed  Insomnia.Core-9.3.0-alpha.3.AppImage
          989173dcd47f20ba50ee1f3e65fbcfc53ad592f90f0b02911cf4584889bdf978  Insomnia.Core-9.3.0-alpha.3.exe
          bc408a7f9ddf45070a26c8ec7fa02d64692f13c779428481d4f4bc404aaa9ee6  Insomnia.Core-9.3.0-alpha.3.zip"
          
          out=$(
          cat <<EOF
          ${test}
          EOF
          )
          
          digest=$(echo "${out}" | base64)
          expected=$(echo "${test}")
          got=$(echo "${digest}" | base64 -d)

          echo "Digest: ${digest}"
          echo "Expected: ${expected}"
          echo "Got: ${got}"
        env:
          ORG: ${{secrets.ORG}}
          PROJECT: ${{secrets.PROJECT}}
          INSOMNIA_TOKEN: ${{secrets.INSOMNIA_TOKEN}}
